# This is a GitLab CI configuration to build the project as a docker image

image:
  name: docker/compose:1.24.0
  entrypoint: ["/bin/sh", "-c"]

stages:
  - build
  - push

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker-compose pull || true
    - docker-compose build
    - docker-compose push web
    - export TAG=$CI_COMMIT_SHA
    - docker-compose build
    - docker-compose push web
  


    # fetches the latest image (not failing if image is not found)
    #- docker pull $CI_REGISTRY_IMAGE:latest || true
    ## builds the project, passing proxy variables, and vcs vars for LABEL
    ## notice the cache-from, which is going to use the image we just pulled locally
    ## the built image is tagged locally with the commit SHA, and then pushed to 
    ## the GitLab registry
    #- >
      #docker build
      #--pull
      #--build-arg VCS_REF=$CI_COMMIT_SHA
      #--build-arg VCS_URL=$CI_PROJECT_URL
      #--cache-from $CI_REGISTRY_IMAGE:latest
      #--tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
      #.
    #- docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA

# Here, the goal is to tag the "master" branch as "latest"
Push latest:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    # Only "master" should be tagged "latest"
    - master
  script:
    # Because we have no guarantee that this job will be picked up by the same runner 
    # that built the image in the previous step, we pull it again locally
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    # Then we tag it "latest"
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:latest
    # And we push it.
    - docker push $CI_REGISTRY_IMAGE:latest

# Finally, the goal here is to Docker tag any Git tag
# GitLab will start a new pipeline everytime a Git tag is created, which is pretty awesome
Push tag:
  variables:
    GIT_STRATEGY: none
  stage: push
  only:
    # We want this job to be run on tags only.
    - tags
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
