proxy:
  title: Data Science Application Server
  logo-url: file:///opt/shinyproxy/favicon.png
  port: 8080
  landing-page: /app/01_shiny_app_pinval
  authentication: none
  heartbeat-rate: 60000
  heartbeat-timeout: 600000
  docker:
    internal-networking: true
  specs:
  - id: 01_shiny_app_pinval
    display-name: PIN Valuation Report (Production)
    description: Create a report on an individual PIN
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: registry.gitlab.com/ccao-data-science---modeling/shiny_app_pinval:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA
  - id: 02_shiny_app_rpie
    display-name: RPIE Report (ALPHA)
    description: Create a report on an individual PIN
    container-cmd: ["R", "-e", "shiny::runApp('/opt/code.r/')"]
    container-image: registry.gitlab.com/ccao-data-science---modeling/shiny_app_rpie:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAOAPPSRV
  - id: 03_shiny_app_pinval_staging
    display-name: PIN Valuation Report (Staging)
    description: Create a report on an individual PIN
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: registry.gitlab.com/ccao-data-science---modeling/shiny_app_pinval:staging
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA
