proxy:
  title: Data Science Application Server
  logo-url: file:///opt/shinyproxy/favicon.png
  port: 8080
  authentication: none
  heartbeat-rate: 60000
  heartbeat-timeout: 600000
  docker:
    internal-networking: true
  specs:

    # Configuration for PINVAL
  - id: shiny_app_pinval
    display-name: PIN Valuation Report (Production)
    description: Generate a report on an individual PIN (production version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_pinval:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA
  - id: shiny_app_pinval_staging
    display-name: PIN Valuation Report (Staging)
    description: Generate a report on an individual PIN (testing version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_pinval:staging
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA

    # Configuration for township diagnostic
  - id: shiny_app_township_diagnostic
    display-name: Township Diagnostic (Production)
    description: Create a report on a township (production version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_township_diagnostic:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA
  - id: shiny_app_township_diagnostic_staging
    display-name: Township Diagnostic (Staging)
    description: Create a report on a township (testing version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_township_diagnostic:staging
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA

    # Configuration for IC version of PINVAL
  - id: shiny_app_ic_pinval
    display-name: IC PINVAL Report (Production)
    description: Provides RPIE filing information for IC PINs (production version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_ic_pinval:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAOAPPSRV
  - id: shiny_app_ic_pinval_staging
    display-name: IC PINVAL Report (Staging)
    description: Provides RPIE filing information for IC PINs (testing version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_ic_pinval:staging
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAOAPPSRV

    # Configuration for data integrity report
  - id: data_integrity_report
    display-name: Data Integrity Report (Production)
    description: Create a report that checks for data integrity issues (production version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/data_integrity_report:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA
  - id: data_integrity_report_staging
    display-name: Data Integrity Report (Staging)
    description: Create a report that checks for data integrity issues (testing version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/data_integrity_report:staging
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAODATA

  - id: shiny_app_rpie
    display-name: RPIE Report (Alpha)
    description: Fetch the RPIE code for a given PIN
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/shiny_app_rpie:latest
    container-network: shiny_server_proxynet
    container-env-file: /run/secrets/DB_CONFIG_CCAOAPPSRV
