# Set the subpath of the shinyproxy URL
server:
  contextPath: /shiny
  servlet:
    context-path: /shiny

proxy:
  title: Data Science Application Server
  logo-url: file:///${WORKDIR}/favicon.png
  port: 8080
  authentication: none
  heartbeat-rate: 60000
  heartbeat-timeout: 600000
  docker:
    internal-networking: true

  specs:

    # RPIE dashboard config
  - id: rpie_dashboard
    display-name: RPIE Dashboard 
    description: Get aggregate information about RPIE filings 
    container-cmd: ["R", "--no-environ", "-e", "rmarkdown::run('dashboard.Rmd')"]
    container-image: ${CCAO_REGISTRY_URL}/applications/shiny_app_rpie_dashboard:latest
    container-network: shiny_server_net
    container-env-file: /run/secrets/DB_CONFIG

    # Configuration for RPIE app
  - id: rpie
    display-name: RPIE Code Retrieval
    description: Fetch the RPIE code for a given PIN
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/applications/shiny_app_rpie:latest
    container-network: shiny_server_net
    container-env-file: /run/secrets/DB_CONFIG

    # Configuration for IC version of PINVAL
  - id: ic_pinval
    display-name: IC PINVAL Report
    description: Provides RPIE filing information for IC PINs
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/applications/shiny_app_ic_pinval:latest
    container-network: shiny_server_net
    container-env-file: /run/secrets/DB_CONFIG
  - id: ic_pinval_staging
    display-name: IC PINVAL Report (Staging)
    description: Provides RPIE filing information for IC PINs (testing version)
    container-cmd: ["R", "-e", "shiny::runApp('/app/app.R')"]
    container-image: ${CCAO_REGISTRY_URL}/applications/shiny_app_ic_pinval:staging
    container-network: shiny_server_net
    container-env-file: /run/secrets/DB_CONFIG

