version: '3.6'
services:
  shinyproxy:
    build: .
    image: registry.gitlab.com/ccao-data-science---modeling/shiny_server:latest
    container_name: shiny_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - proxynet
    secrets:
      - db_config
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets/config.json:/config.json
    environment:
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_RESTART=true
      - WATCHTOWER_POLL_INTERVAL=120
    restart: always

networks:
  proxynet:

secrets:
  db_config:
    file: secrets/odbc.txt
