version: '3.6'

# x-default defines a template set of config options that are used wherever it
# is applied with <<: *default
x-default: &default
  entrypoint: ["echo", "App Loaded"]
  networks:
    - proxynet
  restart: "no"

# Define the main services: shinyproxy and watchtower
services:

  # Shinyproxy handles the launching of containers
  shinyproxy:
    build: .
    image: ${CCAO_REGISTRY_URL}/services/shiny_server:latest
    container_name: shiny_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - proxynet
    # Environmental variables are loaded from .env file
    environment:
      - CCAO_REGISTRY_URL
      - JAVA_TRUST_STORE_PASSWORD
    secrets:
      - DB_CONFIG
      - DC_CERT

  # Fake app slugs to ensure that shinyproxy always has an image to run
  # x-default defines properties that are copied to each slug
  shiny_app_rpie_dashboard:
    <<: *default
    image: ${CCAO_REGISTRY_URL}/applications/shiny_app_rpie_dashboard:latest
  shiny_app_rpie:
    <<: *default
    image: ${CCAO_REGISTRY_URL}/applications/shiny_app_rpie:latest
  shiny_app_ic_pinval:
    <<: *default
    image: ${CCAO_REGISTRY_URL}/applications/shiny_app_ic_pinval:latest
  shiny_app_ic_pinval_staging:
    <<: *default
    image: ${CCAO_REGISTRY_URL}/applications/shiny_app_ic_pinval:staging

# Define network to be shared between containers
# Subnet is changed so as not to conflict with the CCAO default network
# shiny_monitor_net is imported from the shiny_monitor app. It connects to that
# app's postgres DB for the purpose of tracking entered PINs
networks:
  proxynet:
    ipam:
      config:
        - subnet: 211.27.0.0/16
    name: shiny_server_net

# Database credential files that get shared to individual containers
secrets:
  DB_CONFIG:
    file: secrets/DB_CONFIG
  DC_CERT:
    file: secrets/DC_CERT
