version: '3.6'
services:
  shinyproxy:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        DATA_LOCATION: "/home/dfsnow/data"
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxynet
    secrets:
      - db_config

networks:
  proxynet:

secrets:
  db_config:
    file: secrets/odbc.txt
