version: '3.6'
services:
  shinyproxy:
    build: .
    image: ${CCAO_REGISTRY_URL}/shiny_server:latest
    container_name: shiny_server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    networks:
      - proxynet
    secrets:
      - DB_CONFIG_CCAODATA
      - DB_CONFIG_CCAOAPPSRV
    environment:
      - CCAO_REGISTRY_URL
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./secrets/config.json:/config.json
    environment:
      - WATCHTOWER_INCLUDE_STOPPED=true
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_MONITOR_ONLY=true
      - WATCHTOWER_NO_RESTART=true
      - WATCHTOWER_POLL_INTERVAL=120
    restart: always

  # Fake app slugs to ensure that shinyproxy always has an image to run
  shiny_app_pinval_production:
    image: ${CCAO_REGISTRY_URL}/shiny_app_pinval:latest
    entrypoint: ["echo", "PINVAL (Production) Loaded"]
    restart: "no"
  shiny_app_rpie:
    image: ${CCAO_REGISTRY_URL}/shiny_app_rpie:latest
    entrypoint: ["echo", "RPIE App Loaded"]
    restart: "no"
  shiny_app_pinval_staging:
    image: ${CCAO_REGISTRY_URL}/shiny_app_pinval:staging
    entrypoint: ["echo", "PINVAL (Staging) Loaded"]
    restart: "no"
  shiny_app_township_diagnostic:
    image: ${CCAO_REGISTRY_URL}/shiny_app_township_diagnostic:latest
    entrypoint: ["echo", "Township Diagnostic (Alpha) Loaded"]
    restart: "no"
  shiny_app_township_diagnostic_staging:
    image: ${CCAO_REGISTRY_URL}/shiny_app_township_diagnostic:staging
    entrypoint: ["echo", "Township Diagnostic (Alpha Staging) Loaded"]
    restart: "no"
  shiny_app_ic_pinval:
    image: ${CCAO_REGISTRY_URL}/shiny_app_ic_pinval:latest
    entrypoint: ["echo", "IC PINVAL (Production) Loaded"]
    restart: "no"
  shiny_app_ic_pinval_staging:
    image: ${CCAO_REGISTRY_URL}/shiny_app_ic_pinval:staging
    entrypoint: ["echo", "IC PINVAL (Staging) Loaded"]
    restart: "no"
  shiny_app_template:
    image: ${CCAO_REGISTRY_URL}/shiny_app_template:latest
    entrypoint: ["echo", "IC PINVAL (Staging) Loaded"]
    restart: "no"

networks:
  proxynet:

secrets:
  DB_CONFIG_CCAODATA:
    file: secrets/CCAODATA.txt
  DB_CONFIG_CCAOAPPSRV:
    file: secrets/CCAOAPPSRV.txt
