on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  release:
    types: [published]

name: docker-build

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup variables
        run: |
          echo "IMAGE_TAG=$(if [ ${{ github.ref_name }} == master ]; then echo latest; else echo ${{ github.ref_name }}; fi)" >> $GITHUB_ENV
          echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: false
          build-args: |
            VCS_NAME=${{ github.repository }}
            VCS_URL=${{ github.server_url}}/${{ github.repository }}
            VCS_REF=${{ github.sha }}
            VCS_REF_SHORT=${{ env.SHA_SHORT }}
            VCS_VER=${{ github.ref_name }}
            VCS_ID=${{ github.repository_id }}
            VCS_NAMESPACE=${{ github.repository_owner }}
